# Generated by Django 5.2.8 on 2026-06-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_apple_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='apple_account_linked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='apple_sub',
        ),
    ]
