# Generated by Django 5.2.8 on 2026-06-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_apple_account_linked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apple_account_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='apple_sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
