# Generated by Django 5.2.8 on 2026-06-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_apple_account_linked_customuser_apple_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apple_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
