# Generated by Django 5.2.8 on 2026-03-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_container_home_room_item_container_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('in_use', 'In-Use'), ('stored', 'Stored')], max_length=20, null=True),
        ),
    ]
