# Generated by Django 5.2.8 on 2026-03-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item_comment_item_created_by_item_in_use_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='in_use_by',
        ),
    ]
