# Generated by Django 5.2.8 on 2026-07-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_backfill_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
