# Generated by Django 5.2.8 on 2026-03-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_item_in_use_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pictures',
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
