# Generated by Django 5.2.8 on 2026-03-29 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_item_pictures_item_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primary_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_users', to='app.home'),
        ),
    ]
