# Generated by Django 5.2.8 on 2026-07-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_itemcheckout'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('name', 'room'), name='unique_item_name_per_room'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('container__isnull', False)), fields=('name', 'container'), name='unique_item_name_per_container'),
        ),
    ]
