# Generated by Django 5.2.8 on 2026-08-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_starredcontainer_starreditem_starredroom'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_name_per_room',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_name_per_container',
        ),
        migrations.AddField(
            model_name='container',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('room__isnull', False)), fields=('name', 'room'), name='unique_item_name_per_room'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('container__isnull', False), ('deleted_at__isnull', True)), fields=('name', 'container'), name='unique_item_name_per_container'),
        ),
    ]
